apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rag3-aug9-2-llama
  janus-idp.io/tekton: rag3-aug9-2-llama
  backstage.io/kubernetes-id: rag3-aug9-2-llama
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rag3-aug9-2-llama
resources: 
- initialize-namespace.yaml
- deployment-model-server.yaml
- service-model-server.yaml
- deployment.yaml
- route.yaml
- service.yaml
- model-config.yaml
- deployment-database.yaml
- service-database.yaml
- database-config.yaml
- rhoai/
