---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: rag3-aug9-2-llama
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rag3-aug9-2-llama 
  name: rag3-aug9-2-llama
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi