apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: rag3-aug9-2-llama
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/maysunfaisal/rag3-aug9-2-llama:877f18f0e82d4dddec28e0079bdf51e0d9093f83@sha256:08f4016c1ca8a8cc6f398b6688cac8f8d90ea6dc865e7559855ed0be69013cbd # use pre-built to bootstrap 
          name: app-inference
